_wandb:
    value:
        cli_version: 0.21.1
        e:
            ettjevdcei8whyzqfekk0t6lawi2qq6h:
                codePath: main.py
                codePathLocal: main.py
                email: gtx2shino@gmail.com
                executable: /Users/shino/my_code/reinforcement/symmetrizer/.venv/bin/python3
                git:
                    commit: 8dae02bee2ba7132ae4fb07e07020767d280842c
                    remote: git@github.com:ElisevanderPol/symmetrizer.git
                host: shinoair.local
                os: macOS-15.6-arm64-arm-64bit-Mach-O
                program: /Users/shino/my_code/reinforcement/symmetrizer/main.py
                python: CPython 3.13.6
                root: /Users/shino/my_code/reinforcement/symmetrizer
                startedAt: "2025-08-18T08:29:34.198545Z"
                writerId: ettjevdcei8whyzqfekk0t6lawi2qq6h
        m: []
        python_version: 3.13.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.13.6
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
actor_lr:
    value: 0.001
critic_lr:
    value: 0.01
epochs:
    value: 10
eps:
    value: 0.2
gamma:
    value: 0.98
hidden_dim:
    value: 128
lmbda:
    value: 0.95
num_episodes:
    value: 500
